### PR TITLE
Stop setting current index local which is nonexistent in ValueTuple deserializer

### LINKED ISSUE #1279: InvalidProgramException on prerelease when first field is a non-numeric type
@mgravell It seems very likely that this one is on me via https://github.com/StackExchange/Dapper/pull/1242. I'll get a full repro and fix it ASAP.

https://www.myget.org/feed/stackoverflow/package/nuget/Dapper/1.60.14 works fine with `(int, string, string, DateTime?, DateTime?, DateTime?, decimal?, DateTime?, string, int?, DateTime?, DateTime?, int?)` rows.

With `(string, byte[], byte[])`, it breaks:

> System.InvalidProgramException:
> Common Language Runtime detected an invalid program.
>    at Deserialize669fc2c6-0ab9-4b1c-ae66-ee2bfbcc0010(IDataReader )
>    at Dapper.SqlMapper.<QueryRowAsync>d__34`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 500

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #1279, a bug introduced in https://github.com/StackExchange/Dapper/pull/1242.

@mgravell I'm sorry I broke master. Hopefully the fix is super easy to review.

### CODE REVIEW

File: Dapper/SqlMapper.cs [hunk 1]
```diff
@@ -3379,7 +3383,7 @@ private static void GenerateDeserializerFromMap(Type type, IDataReader reader, i
             }
             il.MarkLabel(allDone);
             il.BeginCatchBlock(typeof(Exception)); // stack is Exception
-            il.Emit(OpCodes.Ldloc_0); // stack is Exception, index
+            il.Emit(OpCodes.Ldloc, currentIndexDiagnosticLocal); // stack is Exception, index
```
Comment (jnm2) [inline Dapper/SqlMapper.cs]: I'm going to submit a PR after this one which requires a LocalBuilder instance to be passed to each stloc and ldloc to make it easier to follow what's happening and to add guardrails for future refactoring.
It would have been hard to ignore the mistake in my first PR if LocalBuilders were passed around instead of using magic indexes without passing them around.

**Comment by jnm2** [comment]
@mgravell The check that failed (WIP) is saying that it needs someone with StackExchange org admin permissions to accept new permissions.

**Comment by mgravell** [comment]
Thanks for resolving so promptly - merged.

**Comment by jnm2** [comment]
@mgravell Using the new prerelease, everything seems to be working as anticipated.

File: Dapper/SqlMapper.cs (hunk 1 above)
Comment (jnm2) [reply Dapper/SqlMapper.cs]: https://github.com/StackExchange/Dapper/pull/1282
